---
name: 'GUAC Ingest'
description: 'Ingest files into GUAC'
branding:
  icon: "shield"
  color: "purple"
author: 'Kusari'
inputs:
  files:
    description: 'path to directory or specific file to ingest'
    required: true
  gql-addr:
    description: 'endpoint for graphql api for GUAC'
    requited: true
  token-url:
    description: 'url for auth token provider'
    requited: true
  client-id:
    description: 'client id for auth token provider'
    requited: true
outputs:
  console_out:
    description: 'raw console output from guacone command'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.gql-addr }}
    - ${{ inputs.token-url }}
    - ${{ inputs.client-id }}
